<?php

return [

	/*
	|--------------------------------------------------------------------------
	| Paths
	|--------------------------------------------------------------------------
	|
	| The relative and absolute paths to the directory where your local
    | attachments are stored.
	|
	*/

    'path' => array(
        'relative' => 'uploads/',
        'absolute' => public_path() . '/uploads/'
    ),

    /*
	|--------------------------------------------------------------------------
	| Attachment query string
	|--------------------------------------------------------------------------
	|
	| Enable this to append a query string to attachment URLs generated by this
    | package. This uses the attachment's updated_at timestamp in UNIX
    | timestamp format.
	|
	*/

    'append_query_string' => TRUE,

	/*
	|--------------------------------------------------------------------------
	| Current user
	|--------------------------------------------------------------------------
	|
	| Closure to return the current user. This is used to set the owner of an
    | attachment.
	|
	*/

	'current_user' => function() {
		return Auth::user();
	},

];
